console.log("second line");
console.log("third line");
console.log("fourth line");
console.log("fiveth line");
console.log("sixth line");
console.log("(REMOTE) seventh line");
console.log("seventh line");
console.log("eighth line");
console.log("nineth line");
console.log("tenth line");
